### ISSUE TITLE
cnn_model installing

### ISSUE THREAD

**Issue by Abhi-0212000** [vinayaksable2399/food-calories-estimation-using-Image-processing#2]
when i tried to run the code on GOOGLE COLAB ...it raised an error that cnn_model is not installed
and i tried to install it using command "!pip install cnn_model"
it again raised an error 
ERROR: Could not find a version that satisfies the requirement cnn_model (from versions: none)
ERROR: No matching distribution found for cnn_model

**Comment by vinayaksable2399** [comment]
cnn_model is not python package. It's .py file in the repo. please check this file. also go through with README file
